# Generated by Django 3.1.5 on 2021-01-10 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_studentsphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='StudentsProjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.projects')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.students')),
            ],
            options={
                'verbose_name': 'Проект студента',
                'verbose_name_plural': 'Проекты студентов',
            },
        ),
    ]
