# Generated by Django 3.1.5 on 2021-01-11 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_projects_studentsprojects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='Название предмета')),
                ('description', models.TextField(verbose_name='Описание предмета')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.AlterField(
            model_name='studentsphoto',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.students'),
        ),
        migrations.AlterField(
            model_name='studentsprojects',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projcets', to='main.projects'),
        ),
        migrations.AlterField(
            model_name='studentsprojects',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main.students'),
        ),
    ]
