# Generated by Django 3.1.5 on 2021-01-11 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210111_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsLessons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lessons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lessons')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.students')),
            ],
            options={
                'verbose_name': 'Предмет студента',
                'verbose_name_plural': 'Предметы студентов',
            },
        ),
    ]
