# Generated by Django 3.1.5 on 2021-01-11 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210111_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='Имя заказчика')),
                ('surname', models.TextField(verbose_name='Фамилия заказчика')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='EngineerProjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='Название инженерного проекта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clients')),
            ],
            options={
                'verbose_name': 'Инженерный проетк',
                'verbose_name_plural': 'Инженерные проеткы',
            },
        ),
    ]
