# Generated by Django 3.1.5 on 2021-01-11 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_clients_engineerprojects'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineerprojects',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.students'),
            preserve_default=False,
        ),
    ]
