# Generated by Django 3.1.5 on 2021-01-11 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_engineerprojects_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='Имя заказчика')),
                ('surname', models.TextField(verbose_name='Фамилия заказчика')),
                ('experience', models.IntegerField(verbose_name='Опыт (лет)')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lessons')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='TeachersPhotos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField(verbose_name='Ссылка на фотографию')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teachers')),
            ],
            options={
                'verbose_name': 'Фото преподавателя',
                'verbose_name_plural': 'Фото преподавателей',
            },
        ),
    ]
