# Generated by Django 3.1.5 on 2021-01-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_teachers_teachersphotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='status',
            field=models.CharField(choices=[('y', 'Учится'), ('n', 'Отчсилен')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
