# Generated by Django 3.1.5 on 2021-05-16 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='photo',
            field=models.TextField(default=1, verbose_name='Ссылка на фотографию'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
